### PR TITLE
[doc] redundant web demo

### PR DESCRIPTION
**Pull request by majidaldo**

### CODE REVIEW

**Comment by mwillsey** [comment]
Why is the web demo redundant?

**Comment by majidaldo** [comment]
> Why is the web demo redundant?

there are two links to a web demo. one demo seems to be an old version...the one i deleted.

**Comment by mwillsey** [comment]
Those are two different demos. One is of egg (the one this PR deletes), the other is in a paragraph describing the newer egglog tool, and a demo for that. Despite egg being older, I think the demo still has some value in explaining how it works.

**Comment by majidaldo** [comment]
> Those are two different demos. One is of egg (the one this PR deletes), the other is in a paragraph describing the newer egglog tool, and a demo for that. Despite egg being older, I think the demo still has some value in explaining how it works.

...so it should be explained in the readme.

**Comment by mwillsey** [comment]
Done!

**Pull request closed without merging**
