### PR TITLE
Closes #316 (Was dropping rest of proof)

### LINKED ISSUE #316: Bad explanation when using explain existance
I was seeing weird results so I wrote the following test:

```rust
#[test]
fn simple_explain_exists() {
    //! Same as previous test, but now I want to make a rewrite add some term and see it exists in
    //! more then one step
    use crate::{EGraph, SymbolLang};
    crate::init_logger();

    let rws: Vec<Rewrite<SymbolLang, ()>> = [rewrite!("makeb"; "a" => "b"), rewrite!("makec"; "b" => "c")].iter().cloned().collect();
    let mut egraph = Runner::default().with_explanations_enabled()
        .with_expr(&"a".parse().unwrap())
        .run(&rws).egraph;
    let mut exp = egraph.explain_existance(&"c".parse().unwrap());
    assert_eq!(exp.make_flat_explanation().len(), 3, "Expected 3 steps, got {:?}", exp.make_flat_explanation());
}
```

The explanation I get is
a
c (makec)

So I believe something is amiss. I'll try to look into it, but thought it's better to put it out there for now
@oflatt  I am guessing you are the right person to tag here

### PR DESCRIPTION
**Pull request by eytans**
Added test for existance + fix bad connection choice and… bad drop of `rest_if_proof`

I think this is a full fix, but to be honest I am not sure exactly how everything works, so I hope I am not breaking anything.
`cargo test` passes, and I did run make, but couldn't run with features="lp".

### CODE REVIEW

**Comment by yihozhang** [comment]
This PR seems to be overlooked... @oflatt maybe you could take a look?

**Review by oflatt — APPROVED** [review]
Great catch!
Sorry I've taken so long to respond to this PR, and thanks for adding a test.

**Comment by oflatt** [comment]
@eytans would love to merge this if you have time to fix a small conflict!

**Comment by eytans** [comment]
@oflatt Sure. You can merge now

**Pull request merged**
