### PR TITLE
Add example in doc comment of 'RecExpr'

### PR DESCRIPTION
**Pull request by marcusrossel**
As requested by @oflatt in https://egraphs.zulipchat.com/#narrow/stream/375765-egg.2Fegglog/topic/Replace.20Var.20in.20Pattern/near/430172065

### CODE REVIEW

**Review by oflatt — APPROVED** [review]
Thanks!

**Review by oflatt — CHANGES_REQUESTED** [review]
Looks like you fail the CI (I had to approve the run, I'll change the settings so it always runs in the future)

**Comment by marcusrossel** [comment]
Sorry, I don't understand what the problem is right now. Is there anything I need to do?

**Comment by saulshanabrook** [comment]
I think the formatter is complaining about some whitespace: https://github.com/egraphs-good/egg/actions/runs/8525410185/job/23363979154#step:4:1

If you run "cargo fmt" locally on your branch it should fix it.

**Pull request merged**
